<?php

namespace ContainerL7IoU5A;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMoviesControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\MoviesController' shared autowired service.
     *
     * @return \App\Controller\api\MoviesController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/MoviesController.php';
        include_once \dirname(__DIR__, 4) . '/src/Handlers/GetListOfGenreByMoviesHandler.php';
        include_once \dirname(__DIR__, 4).'/src/Adapter/HttpClientAdapter.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client-contracts/HttpClientInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client/DecoratorTrait.php';
        include_once \dirname(__DIR__, 4).'/vendor/symfony/http-client/UriTemplateHttpClient.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ApiConfigInterface.php';
        include_once \dirname(__DIR__, 4).'/src/Services/ApiConfig.php';
        include_once \dirname(__DIR__, 4) . '/src/Handlers/GetListOfMoviesByGenreHandler.php';

        $a = new \App\Adapter\HttpClientAdapter(new \Symfony\Component\HttpClient\UriTemplateHttpClient(($container->privates['http_client.transport'] ?? $container->load('getHttpClient_TransportService')), NULL, []));
        $b = new \App\Services\ApiConfig(($container->privates['parameter_bag'] ??= new \Symfony\Component\DependencyInjection\ParameterBag\ContainerBag($container)), $container->getEnv('API_TOKEN'), $container->getEnv('API_BASE_URI'), $container->getEnv('API_DEFAULT_LANGUAGE'), $container->getEnv('API_DEFAULT_PAGE'));

        $container->services['App\\Controller\\api\\MoviesController'] = $instance = new \App\Controller\api\MoviesController(new \App\Handler\GetListOfGenreByMoviesHandler($a, $b), new \App\Handler\GetListOfMoviesByGenreHandler($a, $b));

        $instance->setContainer((new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'http_kernel' => ['services', 'http_kernel', 'getHttpKernelService', false],
            'parameter_bag' => ['privates', 'parameter_bag', 'getParameterBagService', false],
            'request_stack' => ['services', 'request_stack', 'getRequestStackService', false],
            'router' => ['services', 'router', 'getRouterService', false],
            'serializer' => ['privates', 'serializer', 'getSerializerService', false],
            'web_link.http_header_serializer' => ['privates', 'web_link.http_header_serializer', 'getWebLink_HttpHeaderSerializerService', false],
        ], [
            'http_kernel' => '?',
            'parameter_bag' => '?',
            'request_stack' => '?',
            'router' => '?',
            'serializer' => '?',
            'web_link.http_header_serializer' => '?',
        ]))->withContext('App\\Controller\\api\\MoviesController', $container));

        return $instance;
    }
}
