# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    api_token: '%env(API_TOKEN)%'
    api_base_uri: '%env(API_BASE_URI)%'
    api_default_language: '%env(API_DEFAULT_LANGUAGE)%'
    api_default_page: '%env(API_DEFAULT_PAGE)%'
    api_image_url: '%env(IMAGE_BASE_URL)%'
services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    App\Adapter\HttpClientAdapterInterface: '@App\Adapter\HttpClientAdapter'
    App\Services\ApiConfig:
        arguments:
                $parameterBag: '@parameter_bag'
                $apiToken: '%api_token%'
                $apiBaseUri: '%api_base_uri%'
                $defaultLanguage: '%api_default_language%'
                $defaultPage: '%api_default_page%'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
